### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by gino-bino** [apilola/tension-tools#9]
Congratulations on this awesome tool. Currently, I have an issue - I can't see the voltage correctly in the 'On Awake' state; it's completely zero. However, in the 'Baked' state, it appears entirely red. I'm using Unity 2023.1.7 HDRP 15.

**Comment by ghost** [comment]
@gino-bino I'm sorry for the delayed response. Did you solve your problem? I would like to help you if you're still having any issues.

**Comment by apilola** [comment]
Sorry, wrong account. :)
